force-app/main/default/objects/Warship__c/Warship__c.object-meta.xml
<CustomObject>
    <label>Warship</label>
    <nameField>
        <label>Warship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warship__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escolha uma opção</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warship__c/fields/Weapons_Status__c.field-meta.xml
<CustomField>
    <fullName>Weapons_Status__c</fullName>
    <label>Weapons Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escolha uma opção</fullName>
            </value>
            <value>
                <fullName>Not Yet Operational</fullName>
                <default>true</default>
                <label>Not Yet Operational</label>
            </value>
            <value>
                <fullName>Fully Operational</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerPages.cls
public with sharing class ControllerPages {
    public ControllerPages(ApexPages.StandardController controller) {
        
    }
    public String Name {get;set;}
    public String Project {get;set;}
    public String WeaponsStatus {get;set;}
    public Date DataFim{get;set;}
    public Integer Milestone{get;set;}
    public Warship__c warship{get;set;}

    
    
    public List<SelectOption> getOpcoesProject(){
        Schema.DescribeFieldResult describeResult = Warship__c.Project_Status__c.getDescribe();
        //Lista as opçoes
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        List<SelectOption> optionToReturn = new List<SelectOption>();
        
        for(Schema.PickListEntry pEntry : entries){
            if(pEntry.isActive()){
                optionToReturn.add(new SelectOption(pEntry.getValue(),pEntry.getLabel()));
            }
        }
        return optionToReturn;
    }
    
    public List<SelectOption> getOpcoesWeaponsStatus(){
        Schema.DescribeFieldResult describeResult = Warship__c.Weapons_Status__c.getDescribe();
        //Lista as opçoes
        List<Schema.PicklistEntry> entries = describeResult.getPickListValues();
        List<SelectOption> optionToReturn = new List<SelectOption>();
        
        for(Schema.PickListEntry pEntry : entries){
            
            if(pEntry.isActive()){
                optionToReturn.add(new SelectOption(pEntry.getValue(),pEntry.getLabel()));
            }
        }
        return optionToReturn;
    }
    
    public void guardarWarship(){
        Warship__c objWarship = new Warship__c();
        objWarship.Name  = Name;
        objWarship.Project_Status__c  = Project;
        objWarship.Weapons_Status__c  = WeaponsStatus;
        objWarship.End_Date__c  = DataFim;
        objWarship.Milestone__c  = Milestone;
        
            try{
                if(objWarship.Project_Status__c != 'Escolha uma opção' && objWarship.Name != null && objWarship.Weapons_Status__c != 'Escolha uma opção'){
                    insert objWarship;
            		
                    ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM,'Warship inserido com sucesso'));
                    Name =null;
                    Project =null;
                    WeaponsStatus =null;
                    Milestone = null;
                    DataFim = null;
                    
            }else{
                    ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.FATAL,'Preencha todos os campos'));
                }
            }catch(DmlException e){
                
            }
        }
}